core v0.0.1
BlockchainExecution/staking_manager pull request #1
Opened 2021-11-10 00:58 UTC by luizcarvalhohen

2021-11-10 18:04 UTC, luca590 requested changes
Good start, it’s quick and dirty which is what we want :+1:.

A couple “rules” to keep it ideally quick but a bit less dirty:
+ Don’t name a class a verb. Name functions verbs and objects nouns (and try to be descriptive)
+ Go ahead and create a simple abstract class when there's a very clear need for it, i.e. if the functions in a given implementation class would be used by (or responsible to) different actors/developers. (SRP)
+ Spend a bit of time to clean up the comments u copy/pasted

2021-11-10 18:04 UTC, luca590 commented on .gitignore
> +/code_src/accounting/
why ignore this accounting dir?

2021-11-10 18:04 UTC, luca590 commented on code_src/accounting/accountingModule.py
> +        return self.substrate.query('System', 'Account', params=[ss58_address]).value
Can you add this comment above line 21

#ss58 reference: https://docs.substrate.io/v3/advanced/ss58/

2021-11-10 18:04 UTC, luca590 commented on code_src/accounting/accountingModule.py
> +    def account_infos(self, ss58_address):
Can you rename this function to something more descriptive and also add comments above for what it does and what it returns

2021-11-10 18:04 UTC, luca590 commented on code_src/accounting/accountingModule.py
> +class Accounting(object):
I think we should rename this class to something like "SubstrateAccount" or maybe "BlockchainAccount"... or possible create an abstract Account class and inherit it to define the methods... Do you have any thoughts on this? It's just "Accounting" is a verb (and whereas this is an object) and it's also very generic, kind of uninformative whereas this class is actually pretty specific

2021-11-10 18:04 UTC, luca590 commented on code_src/accounting/accountingModule.py
> +        self.substrate = substrate_rococo
can you leave the following comment above line 9 and the a 1 sentence explanation for what this line does

"rococo is a testnet for polkadot. Ref: https://polkadot.network/blog/introducing-rococo-polkadots-parachain-testnet/"

2021-11-10 18:04 UTC, luca590 commented on code_src/staking/boundModule.py
> +    def __init__(self, controller_addr, value, reward_address, keypair):
can you comment on the use/context for each of these arguments above line 5

2021-11-10 18:04 UTC, luca590 commented on code_src/staking/boundModule.py
> +        """
Can you clean up this comment (lines 15-32)

2021-11-10 18:04 UTC, luca590 commented on code_src/staking/boundModule.py
> +         (Self::bond) or [`unbond`](Self::unbond) this function does not impose\nany limitation on the amount that
good comment but clean up the new lines

2021-11-10 18:04 UTC, luca590 commented on code_src/staking/chillModule.py
> +class Chill(object):
Rename this class to something that's more descriptive and sounds like an object (i.e. not a verb)

2021-11-10 18:04 UTC, luca590 commented on code_src/staking/chillModule.py
> +    def chill(self):
can you link to some documentation on this function

2021-11-10 18:04 UTC, luca590 commented on code_src/staking/nominatorModule.py
> +class Nominate(object):
Rename to an object, e.g. Nominator

2021-11-10 18:04 UTC, luca590 commented on code_src/staking/setterModule.py
> +class Setter(object):
Can we actually make Setter an abstract class with the function 'set' and create PayeeSetter and ControllerSetter implement the abstract class with the functions you've defined

2021-11-10 18:04 UTC, luca590 commented on code_src/validator/validatorModule.py
> +    def set_invulnerables(self, invulnerables):
Can you comment on the 'invulnerables' type above line 31 with an example. I see it's mentioned in line 34, but it would be helpful to know what the AccountId object really is given it's defined in a dependency

2021-11-10 18:04 UTC, luca590 commented on code_src/validator/validatorModule.py
> +        * `max_nominator_count`: The max number of users who can be a nominator at once.
I don't quite understand this, we're setting the max number of ETH addresses which can simultaneously nominate validators on our behalf? who/what are these "users"?

2021-11-11 19:52 UTC, luizcarvalhohen commented on code_src/accounting/accountingModule.py
> +        self.substrate = substrate_rococo
@luca590 Accounting class will be removed in the next PR i only developed to simulate account management (creation,seed balance ...).

2021-11-15 00:25 UTC, closed without merging